title: Bharat Kusuma
description: Data Scientist · Machine Learning · Statistical Analysis
logo: https://avatars.githubusercontent.com/u/7917104
# theme: jekyll-theme-minimal        # DEFAULT (when no theme is selected): Clean, distraction-free layout for simple documentation.
theme: jekyll-theme-cayman


show_downloads: false

# google_analytics:
